spring.application.name=Makersharks

spring.datasource.url=jdbc:mysql://localhost:3306/makersharks
spring.datasource.username=root
spring.datasource.password=Abu3Abu3@
spring.jpa.hibernate.ddl-auto=update
